/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

/**
 *
 * @author el7se
 */
public class AdministrarDepartamentos extends javax.swing.JFrame {

    /**
     * Creates new form AdministrarDepartamentos
     */
    public AdministrarDepartamentos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAgregarDepto = new javax.swing.JButton();
        btnModificarDpto = new javax.swing.JButton();
        BtnEliminarDpto = new javax.swing.JButton();
        btnBuscarDpto = new javax.swing.JButton();
        lblLogo = new javax.swing.JLabel();
        lblFondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregarDepto.setBackground(new java.awt.Color(102, 0, 0));
        btnAgregarDepto.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnAgregarDepto.setForeground(new java.awt.Color(255, 255, 255));
        btnAgregarDepto.setText("Agregar Departamento");
        getContentPane().add(btnAgregarDepto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 250, -1));

        btnModificarDpto.setBackground(new java.awt.Color(102, 0, 0));
        btnModificarDpto.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnModificarDpto.setForeground(new java.awt.Color(255, 255, 255));
        btnModificarDpto.setText("ModificarDepartamento");
        getContentPane().add(btnModificarDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 250, -1));

        BtnEliminarDpto.setBackground(new java.awt.Color(102, 0, 0));
        BtnEliminarDpto.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        BtnEliminarDpto.setForeground(new java.awt.Color(255, 255, 255));
        BtnEliminarDpto.setText("Eliminar Departamento");
        BtnEliminarDpto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnEliminarDptoActionPerformed(evt);
            }
        });
        getContentPane().add(BtnEliminarDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 300, 250, -1));

        btnBuscarDpto.setBackground(new java.awt.Color(102, 0, 0));
        btnBuscarDpto.setFont(new java.awt.Font("Verdana", 1, 16)); // NOI18N
        btnBuscarDpto.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarDpto.setText("Buscar Departamento");
        getContentPane().add(btnBuscarDpto, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 250, -1));

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo final sin fondo.png"))); // NOI18N
        getContentPane().add(lblLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, -1, -1));

        lblFondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/fondoblanco.jpg"))); // NOI18N
        getContentPane().add(lblFondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnEliminarDptoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnEliminarDptoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnEliminarDptoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarDepartamentos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarDepartamentos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnEliminarDpto;
    private javax.swing.JButton btnAgregarDepto;
    private javax.swing.JButton btnBuscarDpto;
    private javax.swing.JButton btnModificarDpto;
    private javax.swing.JLabel lblFondo;
    private javax.swing.JLabel lblLogo;
    // End of variables declaration//GEN-END:variables
}
