# Generated by Django 3.2.7 on 2021-10-25 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Acompaniantes',
            fields=[
                ('id_acompaniante', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'acompaniantes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id_ciudad', models.BigIntegerField(primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ciudad',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Departamentos',
            fields=[
                ('id_departamento', models.BigIntegerField(primary_key=True, serialize=False)),
                ('departamento', models.CharField(max_length=50)),
                ('n_departamento', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('estado', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'departamentos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id_edificio', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'edificio',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Imagenes',
            fields=[
                ('id_imagen', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=250)),
                ('imagen', models.BinaryField()),
            ],
            options={
                'db_table': 'imagenes',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id_inventario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('valor', models.IntegerField()),
            ],
            options={
                'db_table': 'inventario',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id_perfil', models.FloatField(primary_key=True, serialize=False)),
                ('perfil', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'perfil',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.BigIntegerField(primary_key=True, serialize=False)),
                ('region', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'region',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Reservas',
            fields=[
                ('id_reserva', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_ida', models.DateField()),
                ('fecha_vuelta', models.DateField()),
                ('valor_total', models.IntegerField()),
                ('fecha_ingreso', models.DateField()),
            ],
            options={
                'db_table': 'reservas',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ResponsableServicios',
            fields=[
                ('id_rservicios', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('vehiculo', models.CharField(max_length=100)),
                ('ruta', models.CharField(max_length=100)),
                ('patente', models.CharField(max_length=20)),
                ('nombre_empresa', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'responsable_servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id_servicios', models.FloatField(primary_key=True, serialize=False)),
                ('id_reservas', models.BigIntegerField()),
                ('nombre', models.CharField(max_length=100)),
                ('tipo_servicio', models.CharField(max_length=200)),
                ('horario', models.CharField(max_length=100)),
                ('valor', models.FloatField()),
                ('descripcion', models.CharField(max_length=50)),
                ('multa', models.IntegerField(blank=True, null=True)),
                ('descripcion_multa', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'servicios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('rut', models.CharField(max_length=15)),
                ('appat', models.CharField(max_length=50)),
                ('apmat', models.CharField(max_length=50)),
                ('fecha_ingreso', models.DateField()),
                ('telefono', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsuariosContrasenias',
            fields=[
                ('id_pass', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=50)),
                ('usuario', models.CharField(max_length=25)),
                ('activo', models.CharField(max_length=2)),
                ('fecha_actualizacion', models.DateField()),
            ],
            options={
                'db_table': 'usuarios_contrasenias',
                'managed': False,
            },
        ),
    ]
