# Generated by Django 3.2.7 on 2021-10-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Turismo', '0002_auto_20211030_2259'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='acompanantes',
            options={'managed': False, 'verbose_name': 'Acompanante', 'verbose_name_plural': 'Acompanantes'},
        ),
        migrations.AlterModelOptions(
            name='ciudad',
            options={'managed': False, 'verbose_name': 'Ciudad', 'verbose_name_plural': 'Ciudades'},
        ),
        migrations.AlterModelOptions(
            name='departamentos',
            options={'managed': False, 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='edificio',
            options={'managed': False, 'verbose_name': 'Edificio', 'verbose_name_plural': 'Edificios'},
        ),
        migrations.AlterModelOptions(
            name='imagenes',
            options={'managed': False, 'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='inventario',
            options={'managed': False, 'verbose_name': 'Inventario', 'verbose_name_plural': 'Inventario'},
        ),
        migrations.AlterModelOptions(
            name='perfil',
            options={'managed': False, 'verbose_name': 'Inventario', 'verbose_name_plural': 'Perfiles'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'managed': False, 'verbose_name': 'Region', 'verbose_name_plural': 'Regiones'},
        ),
        migrations.AlterModelOptions(
            name='reservas',
            options={'managed': False, 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
        migrations.AlterModelOptions(
            name='responsableservicios',
            options={'managed': False, 'verbose_name': 'Responsable Servicio', 'verbose_name_plural': 'Responsable Servicios'},
        ),
        migrations.AlterModelOptions(
            name='servicios',
            options={'managed': False, 'verbose_name': 'Servicio', 'verbose_name_plural': 'Servicios'},
        ),
        migrations.AlterModelOptions(
            name='usuarios',
            options={'managed': False, 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.AlterModelOptions(
            name='usuarioscontrasenas',
            options={'managed': False, 'verbose_name': 'Contrasena Usuario', 'verbose_name_plural': 'Contrasenas Usuarios'},
        ),
    ]
